# permissions for end users to edit gpuclusterapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gpuclusterapplication-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ix-gpu-operator
    app.kubernetes.io/part-of: ix-gpu-operator
    app.kubernetes.io/managed-by: kustomize
  name: gpuclusterapplication-editor-role
rules:
- apiGroups:
  - iluvatar.com
  resources:
  - gpuclusterapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iluvatar.com
  resources:
  - gpuclusterapplications/status
  verbs:
  - get
