apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ix-gpu-operator
  labels:
    {{- include "ix-gpu-operator.labels" . | nindent 4 }}
    name: "ix-gpu-operator"
rules:
  - apiGroups: 
    - rbac.authorization.k8s.io
    resources: 
    - clusterroles
    - clusterrolebindings
    verbs: 
    - "*"
  - apiGroups: 
    - ""
    resources: 
    - nodes
    verbs: 
    - get 
    - list
    - watch
    - patch
    - update
  - apiGroups: 
    - ""
    resources: 
    - pods
    - pods/eviction
    - events
    - services
    verbs: 
    - "*"
  - apiGroups: 
    - ""
    resources: 
    - namespaces 
    - serviceaccounts
    verbs: 
    - "*"
  - apiGroups: 
    - apps
    resources: 
    - daemonsets
    verbs: 
    - get
    - list
    - watch
  - apiGroups: 
    - iluvatar.com
    resources: 
    - controllerrevisions
    verbs: 
    - get
    - list
    - watch
  - apiGroups:
    - iluvatar.com
    resources:
    - gpuclusterapplications
    - gpuclusterapplications/status
    - gpuclusterapplications/finalizers
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
    - deletecollection
  - apiGroups:
    - scheduling.k8s.io
    resources:
    - priorityclasses
    verbs:
    - get
    - list
    - watch
    - create
  - apiGroups:
    - coordinator.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete 
  - apiGroups:
    - node.k8s.io
    resources:
    - runtimeclasses
    verbs:
    - get
    - list
    - create
    - update    
    - watch
    - delete
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - watch
    - update
    - patch
    - create
 
