apiVersion: apps/v1
kind: Deployment
metadata:
  name: ix-gpu-operator
  labels:
    {{- include "ix-gpu-operator.labels" . | nindent 4 }}
    name: "ix-gpu-operator"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "ix-gpu-operator"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "ix-gpu-operator"
    spec:
      serviceAccountName: ix-gpu-operator
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.priorityClassName }}
      priorityClassName: {{ .Values.operator.priorityClassName }}
      {{- end}}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 10}}
      {{- end }}
      {{- if .Values.operator.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.operator.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end}}
      containers:
      - name: ix-gpu-operator
        image: {{ include "ix-gpu-operator.image" . }}
        imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
        command: ["ix-gpu-operator"]
        {{- with .Values.operator.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end}}
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: OPERATOR_NAMESPACE
          valueFrom: 
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
          - name: metrics
            containerPort: 8080
      volumes:
      - name: host-os-release
        hostPath:
          path: "/etc/os-release"