kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ix-gpu-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ix-gpu-operator.labels" . | nindent 4 }}
    name: "ix-gpu-operator"
subjects:
  - kind: ServiceAccount
    name: ix-gpu-operator
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: ix-gpu-operator
  apiGroup: rbac.authorization.k8s.io