apiVersion: v1
kind: ServiceAccount
metadata:
  name: ix-gpu-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ix-gpu-operator.labels" . | nindent 4 }}
    name: "ix-gpu-operator"
