apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iluvatar-ix-exporter
  namespace: "Filled By The Configuration"
  labels:
    app.kubernetes.io/name: iluvatar-ix-exporter
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/eviction
  - configmaps
  verbs:
  - get