apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iluvatar-ix-exporter
  namespace: "Filled By The Configuration"
  labels:
    app.kubernetes.io/name: iluvatar-ix-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iluvatar-ix-exporter
subjects:
- kind: ServiceAccount
  name: iluvatar-ix-exporter
  namespace: "Filled By The Configuration"