kind: Service
apiVersion: v1
metadata:
  name: iluvatar-ix-exporter
  namespace: "Filled By The Configuration"
  labels:
    app.kubernetes.io/name: iluvatar-ix-exporter
spec:
  selector:
    app.kubernetes.io/name: iluvatar-ix-exporter
  type: NodePort    
  ports:
  - name: "metrics"
    port: 32021
    targetPort: 32021
    nodePort: 32021