apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iluvatar-device-plugin
  namespace: "Filled By The Configuration"
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/eviction
  verbs:
  - get
  - list
  - watch