apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iluvatar-device-plugin
  namespace: "Filled By The Configuration"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iluvatar-device-plugin
subjects:
- kind: ServiceAccount
  name: iluvatar-device-plugin
  namespace: "Filled By The Configuration"