# Copyright (c) 2024, Shanghai Iluvatar CoreX Semiconductor Co., Ltd.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iluvatar-device-plugin
  namespace: "Filled By The Configuration"
  labels:
    app.kubernetes.io/name: iluvatar-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: iluvatar-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iluvatar-device-plugin
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      priorityClassName: "system-node-critical"
      containers:
      - image: "Filled By The Configuration"
        name: iluvatar-device-plugin-ctr
        securityContext:
          privileged: true
          capabilities:
            drop: ["ALL"]
        livenessProbe:
          exec:
            command:
            - ls
            - /var/lib/kubelet/device-plugins/iluvatar-gpu.sock
          periodSeconds: 5
        startupProbe:
          exec:
            command:
            - ls
            - /var/lib/kubelet/device-plugins/iluvatar-gpu.sock
          periodSeconds: 5
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: udev-ctl
            mountPath: /run/udev
            readOnly: true
          - name: sys
            mountPath: /sys
            readOnly: true
          - name: dev
            mountPath: /dev
          - name: ixc
            mountPath: /ixconfig
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: udev-ctl
          hostPath:
            path: /run/udev
        - name: sys
          hostPath:
            path: /sys
        - name: udev-etc
          hostPath:
            path: /etc/udev/
        - name: dev
          hostPath:
            path: /dev
        - name: ixc
          configMap:
            name: ix-config
